<!DOCTYPE html>
<html>
<head>
    <title>Low Stock Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f0f0f0; }
    </style>
</head>
<body>
    <h2>Low Stock Report</h2>
    <p>Products with current stock at or below 10% of their max IN quantity.</p>
    @if(empty($lowStockData))
        <p>No products with low stock.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Variation</th>
                    <th>SKU</th>
                    <th>Unit</th>
                    <th>Current Stock</th>
                    <th>Max IN</th>
                </tr>
            </thead>
            <tbody>
                @foreach($lowStockData as $row)
                    @foreach($row['variations'] as $variation)
                        <tr>
                            <td>{{ $row['product']->name }}</td>
                            <td>{{ $variation['name'] }}</td>
                            <td>{{ $variation['sku'] }}</td>
                            <td>{{ $variation['unit'] }}</td>
                            <td>{{ $variation['stock'] }}</td>
                            <td>{{ $variation['max_in'] }}</td>
                        </tr>
                    @endforeach
                @endforeach
            </tbody>
        </table>
    @endif
    <p>Generated by: <span>[Your Name/Company]</span></p>
</body>
</html>
