<!DOCTYPE html>
<html>
<head>
    <title>Stock Level Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
        }
    </style>
</head>
<body>
    @if ($errMsg !== "")
        {{ $errMsg }}
    @else
        @if (empty($reportData))
            <p>No data available.</p>
        @else
            <h2>Stock Level Report</h2>
            <p>As of: <span>{{ date('Y-m-d') }}</span></p>
            <table>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $grandTotal = 0;
                    @endphp
                    @foreach ($reportData as $product)
                        <tr>
                            <td colspan="3"><strong>{{ $product->name }}</strong></td>
                        </tr>
                        @php
                            $productTotal = 0;
                        @endphp
                        @foreach ($product->variations as $variation)
                            <tr>
                                <td>{{ $variation->name }}</td>
                                <td>{{ $variation->stock }}</td>
                                <td>{{ $variation->unit }}</td>
                            </tr>
                            @php
                                $productTotal += $variation->stock;
                                $grandTotal += $variation->stock;
                            @endphp
                        @endforeach
                        <tr>
                            <td colspan="2">Subtotal for {{ $product->name }}:</td>
                            <td>{{ $productTotal }}</td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">Grand Total:</td>
                        <td>{{ $grandTotal }}</td>
                    </tr>
                </tfoot>
            </table>
            <p>Generated by: <span>[Your Name/Company]</span></p>
        @endif
    @endif
</body>
</html>