<!DOCTYPE html>
<html>
<head>
    <title>Stock Movement Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
        }
        .badge-in {
            color: #fff;
            background: #009688;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 0.9em;
        }
        .badge-out {
            color: #fff;
            background: #f44336;
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 0.9em;
        }
        .center-align {
            text-align: center;
        }
        .grey-text {
            color: #888;
        }
    </style>
</head>
<body>
    <h2>Stock Movement Report</h2>
    <p>
        @if($dateFrom && $dateTo)
            Period: {{ $dateFrom }} to {{ $dateTo }}
        @elseif($dateFrom)
            From: {{ $dateFrom }}
        @elseif($dateTo)
            To: {{ $dateTo }}
        @else
            All Dates
        @endif
    </p>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Product</th>
                <th>Variation</th>
                <th>Batch</th>
                <th>Qty</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $tx)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($tx->transaction_date)->format('Y-m-d H:i') }}</td>
                    <td>
                        @if($tx->transaction_type == 'in')
                            <span class="badge-in">{{ strtoupper($tx->transaction_type) }}</span>
                        @else
                            <span class="badge-out">{{ strtoupper($tx->transaction_type) }}</span>
                        @endif
                    </td>
                    <td>{{ $tx->stockBatch->productVariation->product->name ?? '-' }}</td>
                    <td>{{ $tx->stockBatch->productVariation->name ?? '-' }}</td>
                    <td>{{ $tx->stockBatch->batch_number ?? '-' }}</td>
                    <td>{{ $tx->quantity }}</td>
                    <td>{{ $tx->remarks }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="center-align grey-text">No transactions found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    <p>Generated by: <span>[Your Name/Company]</span></p>
</body>
</html>
